name: Run Cypress Component Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  cypress-component-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress Component Tests
        uses: cypress-io/github-action@v6
        with:
          component: true
